### ISSUE TITLE
Create a block_device abstraction

### ISSUE THREAD

**Issue by psarna** [psarna/seastar#1]
1. Create an abstraction layer for accessing a block device, similar to `seastar::file`, but with a reduced interface (open, read, write, close, flush for a start).

2. Add the initial implementation which uses a `seastar::file` instance underneath, created by opening a device file directly (e.g. `open_file_dma(/dev/sdb)`).

3. Write a first batch of unit tests, which check if the device is read from and written to correctly. The tests can take a path parameter which is expected to be a block device, e.g. `/dev/sdb`.

**Comment by varqox** [comment]
@psarna 
I have a problem with running my unit test in the test suite:
```
$ ./test.py --mode=dev --name=block
['cmake', '/home/quasar/src/zpp/seastar/build/dev', '-DSeastar_TEST_TIMEOUT=300', '-DSeastar_EXECUTE_ONLY_FAST_TESTS=no', '-DSeastar_UNIT_TEST_SMP=2', '-DSeastar_JENKINS=']
-- Could NOT find dpdk (missing: dpdk_INCLUDE_DIR dpdk_PMD_VMXNET3_UIO_LIBRARY dpdk_PMD_I40E_LIBRARY dpdk_PMD_IXGBE_LIBRARY dpdk_PMD_E1000_LIBRARY dpdk_PMD_BNXT_LIBRARY dpdk_PMD_RING_LIBRARY dpdk_PMD_CXGBE_LIBRARY dpdk_PMD_ENA_LIBRARY dpdk_PMD_ENIC_LIBRARY dpdk_PMD_NFP_LIBRARY dpdk_PMD_QEDE_LIBRARY dpdk_RING_LIBRARY dpdk_KVARGS_LIBRARY dpdk_MEMPOOL_LIBRARY dpdk_MEMPOOL_RING_LIBRARY dpdk_HASH_LIBRARY dpdk_CMDLINE_LIBRARY dpdk_MBUF_LIBRARY dpdk_CFGFILE_LIBRARY dpdk_EAL_LIBRARY dpdk_ETHDEV_LIBRARY dpdk_NET_LIBRARY dpdk_TIMER_LIBRARY dpdk_PCI_LIBRARY dpdk_BUS_PCI_LIBRARY dpdk_BUS_VDEV_LIBRARY dpdk_PMD_FM10K_LIBRARY dpdk_PMD_SFC_EFX_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/quasar/src/zpp/seastar/build/dev
['ctest', '/home/quasar/src/zpp/seastar/build/dev', '-E', 'Seastar.dist', '--output-on-failure', '-R', 'block']
Test project /home/quasar/src/zpp/seastar/build/dev
    Start 6: Seastar.unit.block_device
1/1 Test #6: Seastar.unit.block_device ........***Failed    6.93 sec
[1/3] Building CXX object tests/unit/CMakeFiles/test_unit_block_device.dir/block_device_test.cc.o
[2/3] Linking CXX executable tests/unit/block_device_test
[2/3] cd /home/quasar/src/zpp/seastar/build/dev/tests/unit && /home/quasar/src/zpp/seastar/build/dev/tests/unit/block_device_test -- -c 2
error: too many positional options have been specified on the command line

Try --help.
FAILED: tests/unit/CMakeFiles/test_unit_block_device_run 
cd /home/quasar/src/zpp/seastar/build/dev/tests/unit && /home/quasar/src/zpp/seastar/build/dev/tests/unit/block_device_test -- -c 2
ninja: build stopped: subcommand failed.


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   6.93 sec

The following tests FAILED:
	  6 - Seastar.unit.block_device (Failed)
Errors while running CTest
Traceback (most recent call last):
  File "./test.py", line 68, in <module>
    run_tests(mode)
  File "./test.py", line 65, in run_tests
    subprocess.check_call(CTEST_ARGS, shell=False, cwd=BUILD_PATH)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ctest', '/home/quasar/src/zpp/seastar/build/dev', '-E', 'Seastar.dist', '--output-on-failure', '-R', 'block']' returned non-zero exit status 8.
```
 I process command-line arguments in the same way as e.g. `directory_test` that runs without problems.
https://github.com/psarna/seastar/blob/d38dd0464122efafe5763292a3e9f0f5d3af710c/tests/unit/block_device_test.cc#L104-L115

Can you help me with making it work?

**Comment by psarna** [comment]
The issue is that your patch configures the test as a boost test case, while it is a special kind of test which provides its own `main` function. In `tests/unit/CMakeLists.txt`, you declared the test case via the `seastar_add_test` procedure, while `test_directory` is declared with `seastar_add_app_test`:
```cmake
seastar_add_app_test (directory
  SOURCES directory_test.cc)
```
The solution is to simply use `seastar_add_app_test` for declaring your test case in cmake, then `test.py` will not try to run it with unnecessary boost-specific command line arguments.
